### ISSUE TITLE
question about bioargo data

### ISSUE THREAD

**Issue by rj678** [iuryt/NorthAtlanticBloom#4]
hello - thank you for releasing this repo - I have a basic question about the input data:

the script `preprocess_external.py` refers to a path: `fnames = glob("../../data/external/bioargo/*")`

in the references of your paper, you link to this site: https://archimer.ifremer.fr/doc/00445/55637/

could you please direct me to the full set of files to download and place under `bioargo/*` for this repo

I downloaded BGC sprof data files, but there are quite a few folders there

thank you and I look forward to learning more from your paper and your code

**Comment by iuryt** [comment]
Hi, 

Thank you for using this repository! Don't hesitate to create issues. This is definitely an issue because I should have been more clear about how to access the BGC Argo data. For the purpose of the reproducibility of this code, I simply added the files to the repository because they are very small. Thus, just do `git pull` and you should have the files.

If in the future you are not sure if your question is defined as an issue, I just setup a discussions forum for general questions.
https://github.com/iuryt/NorthAtlanticBloom/discussions

I don't remember exactly how I obtained these files, but probably I used the [ERDDAP server](https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats-synthetic-BGC.graph?longitude,latitude,time&.draw=markers&.colorBar=%7CD%7C%7C%7C%7C) from Infremer

If this is too complicated, you can also check out if [project ArgoPy](https://github.com/euroargodev/argopy) has implemented BGC Argo data, but this is going to generate files in a different organization and with different names for the variables.

Hope this has helped you.
